on:
  push:
    branches:
      - 'main'
    paths:
      - database.sql
      - tests/**
  pull_request:
    paths:
      - database.sql
      - tests/**

name: Test schema

jobs:
    test:
      name: Test
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres:15
          env:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432

      steps:
        - name: Checkout sources
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Test with pytest
          run: |
            pytest tests
          env:
            DATABASE_NAME: postgres
            DATABASE_USER: postgres
            DATABASE_PASSWORD: password
            DATABASE_HOST: localhost
            DATABASE_PORT: 5432
